### ISSUE TITLE
Enhancement: configuration profile resource

### ISSUE THREAD

**Issue by ecanault** [Yohan460/terraform-provider-jamf#11]
- Add the site name, not only the ID, like for groups resources for example
- Add the Self Service notification check box

**Comment by Yohan460** [comment]
>Add the site name, not only the ID, like for groups resources for example

The Jamf API requires the site ID in the API call. We won't be modifying the schema due to this. The workaround would be to use a terraform data reference on the site once it's supported.

> Add the Self Service notification check box

Would you be able to provide examples of the API call xml you'd be looking to replicate

**Comment by ecanault** [comment]
Hi,

For Sites, see this #15 if it can help?

For Self Service notification check box (same logic for policies here #10), the API seems buggy as I don't understand how it can handle twice the same key `notification`:
```
    <self_service>
      <self_service_display_name>test</self_service_display_name>
      <install_button_text>Install</install_button_text>
      <self_service_description/>
      <force_users_to_view_description>true</force_users_to_view_description>
      <security>
        <removal_disallowed>Never</removal_disallowed>
      </security>
      <self_service_icon/>
      <feature_on_main_page>false</feature_on_main_page>
      <self_service_categories/>
      <notification>false</notification>
      <notification>Self Service</notification>
      <notification_subject/>
      <notification_message/>
    </self_service>
```

I tried to play a little with that but did not managed to obtain a working solution .So I'm not able to provide valid examples.
It's perhaps better to close this issue for the moment or to pause it.
