### ISSUE TITLE
Enhancement: new API endpoints

### ISSUE THREAD

**Issue by ecanault** [Yohan460/terraform-provider-jamf#12]
Of course it could be extended to all API endpoints , but
these ones are mandatory in my opinion :

- Sites
- Extension attributes
- Packages (upload)
- Network segments
- Buildings
- Departments
- User groups

**Comment by Yohan460** [comment]
We already have the following:
* Buildings
* Departments

As for `Packages (upload)`. That is not something that is documented by the Jamf API at this point in time

@forevanyeung is already working on extension attribute support in https://github.com/Yohan460/terraform-provider-jamf/pull/14. 

I'm open to PRs to add support. If you don't wish to write the PR, then please open a new issue with accurate information
