### ISSUE TITLE
To check: new API URI and limitations

### ISSUE THREAD

**Issue by ecanault** [Yohan460/terraform-provider-jamf#13]
Not sure about that but it seems that this project new API URLs are <https://instance.jamfcloud.com/uapi/vX/...> instead of <https://instance.jamfcloud.com/api/vX/...>

Also: for some endpoints in new Jamf Pro API (like categories for example), there is a page size limit. I did not have any issues with that but if I remember well you could not list more than 2000 object per page (Jamf Pro limitation), and the default is 100.

**Comment by Yohan460** [comment]
This sounds like more of an issue with the [yohan460/go-jamf-api](https://github.com/yohan460/go-jamf-api) repo than this one. Please re-post the issue there if applicable
