### ISSUE TITLE
Create New Release for recent Jamf OAuth changes

### ISSUE THREAD

**Issue by ryangoldblatt-bm** [Yohan460/terraform-provider-jamf#27]
Could we please get a new provider release so I can pull the OAuth changes added here? https://github.com/Yohan460/terraform-provider-jamf/commit/51955040d807ee53556ce7f19d672deb1aa0eab7

I am currently finalising some Github Workflows and would like to utilise using specific Jamf API client roles for `terraform plan` and `terraform apply` jobs i.e. read only role for plan and read/write role for apply.

**Comment by Yohan460** [comment]
Yeah, I’ll get one updated and released on Monday. Thanks for the bump

**Comment by Yohan460** [comment]
[v1.0.17](https://github.com/Yohan460/terraform-provider-jamf/releases/tag/v1.0.17) has been released

**Comment by ryangoldblatt-bm** [comment]
> [v1.0.17](https://github.com/Yohan460/terraform-provider-jamf/releases/tag/v1.0.17) has been released

Awesome, thank you!
